### PR TITLE
add support for importing only certain issues

### PR DESCRIPTION
**Pull request by glensc**
i have in trac multiple projects, which in gitlab are separate project.
so i needed to import only tickets that are related to git project.

### CODE REVIEW

**Comment by moimael** [comment]
Thanks for your contribution, I'm in Holliday right now so I'll have a look in a few days !

**Comment by moimael** [comment]
So you just specify manually all issues you want to import ? it seems really unusable with a lot of issues.

**Comment by glensc** [comment]
well. "manually" in context that they are written to .cfg; but i have svn2git converter that writes out that syntax of referenced ticket ids.

**Comment by moimael** [comment]
Ok that make sense :)

**Pull request merged**
